name = "stm32f407disco_demos"
description = ""
version = "0.1.0"

authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = "https://github.com/GNAT-Academic-Program/stm32f407disco_demos"
tags = []

auto-gpr-with = false
project-files = [
"blinky/blinky.gpr",
"blinky_tasks_0/blinky_tasks_0.gpr",
"blinky_protected_0/blinky_protected_0.gpr",
]

[[depends-on]]
light_tasking_stm32f407 = "*"
stm32f407_hal = "*"
stm32f407disco_bsp = "*"
hal = "*"

[origin]
commit = "0529d3110699b083381cc299a3445cf88bc35cec"
url = "git+https://github.com/GNAT-Academic-Program/stm32f407disco_demos.git"